const $ = (id) => document.getElementById(id);
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {overview:'Overview',spatial:'Spatial navigation',telemetry:'Telemetry & alarms',analytics:'Analytics & maintenance',simulation:'Simulation & process',controls:'Remote controls',integrations:'Integrations & lineage',governance:'Roles & audit'};
const categoryColors = ['#6488ff','#b773f1','#5bd3a8','#ff9a65','#9aa8c6'];
const sampleAt = (minute, base) => ({
  temperature: +(base.temperatureC + Math.sin(minute/7)*1.2 + (minute>48 ? 1.1 : 0)).toFixed(1),
  humidity: Math.round(base.humidityPercent + Math.sin(minute/9)*3),
  power: +(base.powerKw + Math.sin(minute/5)*2.3 + (minute>45 ? 2.1 : 0)).toFixed(1),
  vibration: +(2.1 + Math.sin(minute/6)*.35 + (minute>48 ? .55 : 0)).toFixed(2),
  uptime: 99.7,
  throughput: Math.round(148 + Math.sin(minute/8)*11)
});
const band = (item, bounds) => {
  if (!item?.bounds) return 'Unknown';
  const z = (item.bounds[0][2] + item.bounds[1][2])/2;
  return z < bounds.lower ? 'Lower band' : z < bounds.upper ? 'Middle band' : 'Upper band';
};
function line(values, color='actual') {
  const min=Math.min(...values)-1, max=Math.max(...values)+1;
  const points=values.map((v,i)=>`${(i/(values.length-1)*280).toFixed(1)},${(104-(v-min)/(max-min)*85).toFixed(1)}`).join(' ');
  return `<polyline class="${color}" points="${points}"/>`;
}
function chart(values, baseline=null) {
  return `<svg class="chart" viewBox="0 0 280 115" preserveAspectRatio="none" role="img" aria-label="Sample time-series chart"><path class="gridline" d="M0 30H280 M0 60H280 M0 90H280"/>${baseline?line(baseline,'baseline'):''}${line(values)}</svg>`;
}
function download(name, value, type) {
  const url=URL.createObjectURL(new Blob([value],{type})); const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function createDashboard({manifest,telemetry,relationships,actions}) {
  const entries=manifest.elements;
  const byGuid=new Map(entries.map(e=>[e.guid,e]));
  const storeyByGuid=new Map(relationships.elements.map(e=>[e.guid,e.storey]));
  const storeyNameByGuid=new Map(relationships.spatial.filter(e=>e.ifcClass==='IfcBuildingStorey').map(e=>[e.guid,e.name]));
  const elevations=entries.map(e=>(e.bounds[0][2]+e.bounds[1][2])/2).sort((a,b)=>a-b);
  const bounds={lower:elevations[Math.floor(elevations.length/3)],upper:elevations[Math.floor(elevations.length*2/3)]};
  const state={view:'overview',minute:60,compare:'off',playing:false,selected:null,selectedMany:new Set(),category:null,query:'',metric:'temperature',filter:false,mapLayer:'temperature',geofence:false,incidents:[
    {id:1,severity:'warning',title:'Supply fan vibration above baseline',minute:51,ack:false,cleared:false,cause:'Air handling → bearing wear → rising vibration'},
    {id:2,severity:'info',title:'Power demand shift',minute:44,ack:false,cleared:false,cause:'Electrical → load schedule → evening ramp'},
    {id:3,severity:'critical',title:'Temperature threshold rehearsal',minute:59,ack:false,cleared:false,cause:'HVAC → cooling loop → high simulated setpoint'}
  ],autoAlerts:new Set(),sim:{load:70,ambient:24,speed:80,flow:65,running:false,fast:false,progress:0,runA:null,runB:null},control:{fan:false,valve:42,setpoint:22,interlock:true},role:'Viewer',audit:[],workOrders:[],feedback:[],endpoints:[]};
  let toastTimer,playTimer,simTimer;
  const current=()=>sampleAt(state.minute,telemetry);
  function toast(message){const el=$('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500)}
  function audit(action){state.audit.unshift({time:new Date().toLocaleTimeString(),role:state.role,action});state.audit=state.audit.slice(0,40)}
  function head(kicker,title,desc){return `<div class="panel-head"><span class="dt-eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div>`}
  const metric=(label,value,unit,foot='',tone='')=>`<div class="kpi sc-metric ${tone}"><span class="sc-metric__label">${label}</span><div class="sc-metric__reading"><strong class="sc-metric__value">${value}</strong><span class="sc-metric__unit">${unit}</span></div><small class="sc-metric__meta">${foot}</small></div>`;
  const section=(title,content,link='')=>`<section class="panel-section"><div class="panel-title"><strong class="sc-section-title">${title}</strong>${link}</div>${content}</section>`;
  const incidentHtml=(item,full=false)=>`<div class="incident ${item.severity}"><strong>${esc(item.title)}</strong><small>${item.severity.toUpperCase()} · sample T−${60-item.minute} min · ${item.ack?'Acknowledged':'Unacknowledged'}</small>${full?`<details class="tree-group"><summary>Root cause tree</summary><div class="tree-items">${item.cause.split('→').map((node,i)=>`<div class="cause-node">${'↳ '.repeat(i)}${esc(node.trim())}</div>`).join('')}</div></details><div class="small-actions"><button class="dt-button" data-action="ack" data-id="${item.id}" ${item.ack?'disabled':''}>Acknowledge</button><button class="dt-button" data-action="clear" data-id="${item.id}">Clear</button></div>`:''}</div>`;
  function overview(){const s=current();return head('01 / OPERATIONS','Building overview','The model leads. Sample operational signals stay close at hand.')+
    `<div class="mini-stats"><div class="mini-stat"><span>IFC elements</span><strong>${entries.length.toLocaleString()}</strong></div><div class="mini-stat"><span>Categories</span><strong>${Object.keys(manifest.counts).length}</strong></div></div>`+
    section('Live KPI dashboard <span class="sample-mini">SIMULATED</span>',`<div class="kpi-grid">${metric('Indoor temperature',s.temperature,'°C','Threshold 24 °C',s.temperature>24?'attention':'')}${metric('Power demand',s.power,'kW','Threshold 22 kW',s.power>22?'attention':'')}${metric('Vibration',s.vibration,'mm/s','Threshold 2.8 mm/s',s.vibration>2.8?'attention':'')}${metric('Uptime',s.uptime,'%','Sample target 99.5%')}</div>`) +
    section('System state',`<div class="metric-line"><span>Sensor feed</span><span class="pill warn">Simulated</span></div><div class="metric-line"><span>Model geometry</span><span class="pill good">Loaded</span></div><div class="metric-line"><span>Microsoft Fabric</span><span class="pill">Unconnected</span></div>`) +
    section('Active incidents',state.incidents.filter(i=>!i.cleared).slice(0,2).map(i=>incidentHtml(i)).join('')||'<p class="muted">No active sample incidents.</p>',`<button class="text-button" data-go="telemetry">View all ↗</button>`)+
    `<button class="dt-button full" data-go="spatial">Explore asset tree →</button>`;
  }
  function spatial(){const groups=Object.entries(manifest.counts).sort((a,b)=>b[1]-a[1]);const matches=entries.filter(e=>(!state.category||e.type===state.category)&&(e.name.toLowerCase().includes(state.query.toLowerCase())||e.guid.toLowerCase().includes(state.query.toLowerCase()))).slice(0,35);return head('02 / SPATIAL','Asset navigation','Find, isolate, frame, and compare model components.')+
    section('Facility → IFC class → asset',`<label class="dt-field">Quick search<input class="dt-input" id="asset-search" type="search" placeholder="Name or IFC GUID" value="${esc(state.query)}" /></label><div class="result-list">${matches.map(e=>`<button data-action="select" data-guid="${esc(e.guid)}">${esc(e.name)}<small>${esc(e.type)} · ${esc(e.guid)}</small></button>`).join('')||'<p class="muted">No matching assets.</p>'}</div>`) +
    section('IFC classes',`<div class="list"><button class="list-item ${!state.category?'active':''}" data-action="category" data-category="all">All categories <span class="count">${entries.length}</span></button>${groups.map(([name,count],i)=>`<button class="list-item ${state.category===name?'active':''}" data-action="category" data-category="${name}"><span class="swatch" style="--swatch:${categoryColors[i%5]}"></span>${esc(name.replace(/^Ifc/,''))}<span class="count">${count}</span></button>`).join('')}</div>`) +
    section('Facility / Sample Building asset tree',`<div class="note-box">Facility → IFC class → asset</div>${groups.slice(0,8).map(([name,count])=>`<details class="tree-group"><summary>${esc(name.replace(/^Ifc/,''))} · ${count}</summary><div class="tree-items">${entries.filter(e=>e.type===name).slice(0,12).map(e=>`<button data-action="select" data-guid="${esc(e.guid)}">${esc(e.name)}</button>`).join('')}</div></details>`).join('')}`) +
    section('Multi-asset selection',`<p class="muted">Add selected assets to a working set, then isolate them in the viewport.</p><div class="metric-line"><span>Working set</span><strong>${state.selectedMany.size} assets</strong></div><div class="small-actions"><button class="dt-button" data-action="add-selection" ${!state.selected?'disabled':''}>Add selected</button><button class="dt-button" data-action="isolate-set" ${!state.selectedMany.size?'disabled':''}>Isolate set</button><button class="dt-button" data-action="clear-set">Clear</button></div>`) +
    section('GIS & map overlay',`<div class="map-card ${state.geofence?'geofenced':''}" style="--heat-color:${state.mapLayer==='temperature'?'#f16c92':state.mapLayer==='weather'?'#6488ff':'#ff9a65'}"><span class="map-point" style="left:${47+Math.sin(state.minute/8)*8}%;top:${43+Math.cos(state.minute/9)*7}%"></span><span class="map-label">Sample Building · illustrative site</span></div><div class="metric-line"><span>Region aggregate</span><strong>${state.mapLayer==='temperature'?`${current().temperature} °C`:state.mapLayer==='traffic'?`${current().throughput} visits/h`:'Mild · sample'}</strong></div><label class="dt-field">Heatmap layer<select class="dt-input" id="map-layer"><option value="temperature" ${state.mapLayer==='temperature'?'selected':''}>Temperature</option><option value="weather" ${state.mapLayer==='weather'?'selected':''}>Weather</option><option value="traffic" ${state.mapLayer==='traffic'?'selected':''}>Traffic</option></select></label><div class="small-actions"><button class="dt-button" data-action="map-toggle">${$('map-overlay').hidden?'Show':'Hide'} overlay</button><button class="dt-button" data-action="geofence">Geofence ${state.geofence?'on':'off'}</button></div><p class="muted">The synthetic IFC has no georeferenced coordinates or GPS feed. Region aggregation and tracking are illustrative.</p>`);
  }
  function telemetryPanel(){const readings=Array.from({length:61},(_,i)=>sampleAt(i,telemetry));const values=readings.map(x=>x[state.metric]);const filter=state.filter?values.map((v,i)=>(values[Math.max(0,i-1)]+v+values[Math.min(values.length-1,i+1)])/3):values;const s=current();return head('03 / MONITORING','Telemetry & alarms','Sample streaming, thresholds, trends, and incident triage.')+
    section('Time travel',`<div class="small-actions"><button class="dt-button" data-action="time-play" id="time-play" type="button">${state.playing?'Ⅱ Pause':'▶ Play'}</button><button class="dt-button" data-action="replay-incident" type="button">↶ Incident −5 min</button></div><p class="muted" id="time-label"></p><input id="time-slider" class="range" type="range" min="0" max="60" value="${state.minute}" aria-label="Minutes from start of sample history" /><label class="dt-field">Compare<select id="compare-time" class="dt-input"><option value="off" ${state.compare==='off'?'selected':''}>Off</option><option value="30" ${state.compare==='30'?'selected':''}>−30 min</option><option value="0" ${state.compare==='0'?'selected':''}>−60 min</option></select></label><div class="metric-line"><span>Temperature difference</span><strong id="time-diff">—</strong></div>`) +
    section('Sensor data streamer',`<label class="dt-field">Signal<select class="dt-input" id="metric-select">${['temperature','power','vibration','humidity','throughput'].map(m=>`<option value="${m}" ${state.metric===m?'selected':''}>${m[0].toUpperCase()+m.slice(1)}</option>`).join('')}</select></label><div class="metric-line"><span>At selected time</span><strong id="telemetry-current">${s[state.metric]} ${({temperature:'°C',power:'kW',vibration:'mm/s',humidity:'%',throughput:'units/h'})[state.metric]}</strong></div>${chart(filter)}<div class="legend"><span><b style="background:#be8742"></b>Sample history</span></div><div class="small-actions"><button class="dt-button" data-action="noise">Noise filter ${state.filter?'on':'off'}</button><button class="dt-button" data-action="csv">CSV ↓</button><button class="dt-button" data-action="json">JSON ↓</button></div>`) +
    section('Threshold controls',`<div class="metric-line"><span>Temperature</span><strong>24 °C</strong></div><div class="metric-line"><span>Vibration</span><strong>2.8 mm/s</strong></div><div class="metric-line"><span>Power demand</span><strong>22 kW</strong></div><button class="dt-button full" data-action="trigger-alarm">Trigger sample alert</button>`) +
    section('Alarm & incident management',state.incidents.filter(i=>!i.cleared).map(i=>incidentHtml(i,true)).join('')||'<p class="muted">No active incidents.</p>');
  }
  function analytics(){const s=current();const wear=Math.min(100,Math.round(14+s.vibration*5));const health=100-wear;const rul=Math.round(320-wear*2.2);const values=Array.from({length:30},(_,i)=>100-i*(wear/30));const actual=Array.from({length:30},(_,i)=>22+Math.sin(i/4)+i*.04);return head('04 / ANALYTICS','Predictive analytics','Illustrative model outputs computed from sample readings.')+
    section('Predictive maintenance',`<div class="kpi-grid">${metric('Health index',health,'/100','Sample score',health<80?'attention':'')}${metric('Remaining life',rul,'days','Illustrative estimate')}</div><p class="muted">Degradation curve · supply fan bearing</p>${chart(values)}<div class="metric-line"><span>Likely failure mode</span><strong>Bearing wear</strong></div><button class="dt-button full" data-action="work-order">Generate demo work order</button><p class="muted">No trained ML model or CMMS connection is installed.</p>`) +
    section('Anomaly detection',`<div class="metric-line"><span>Model confidence</span><strong>87% sample</strong></div><div class="progress"><i style="width:87%"></i></div>${chart(actual,Array.from({length:30},()=>22))}<div class="legend"><span><b style="background:#88ad9b"></b>Baseline</span><span><b style="background:#be8742"></b>Actual</span></div><div class="metric-line"><span>Deviation</span><strong>${(s.temperature-22).toFixed(1)} °C</strong></div><div class="small-actions"><button class="dt-button" data-action="feedback" data-value="valid">Valid anomaly</button><button class="dt-button" data-action="feedback" data-value="false-positive">False positive</button></div><p class="feedback">${state.feedback.length} feedback labels in this session.</p>`);
  }
  function simulation(){const v=state.sim;const outcome=simulate(v);return head('05 / WHAT-IF','Scenario engine','Adjust a virtual operating state and compare results.')+
    section('Simulation controls',`<div class="stack"><label class="dt-field">Load <output>${v.load}%</output><input class="range" data-sim="load" type="range" min="30" max="120" value="${v.load}" /></label><label class="dt-field">Ambient temperature <output>${v.ambient} °C</output><input class="range" data-sim="ambient" type="range" min="10" max="40" value="${v.ambient}" /></label><label class="dt-field">Equipment speed <output>${v.speed}%</output><input class="range" data-sim="speed" type="range" min="20" max="120" value="${v.speed}" /></label></div><div class="small-actions"><button class="dt-button dt-button--primary" data-action="sim-run">${v.running?'Pause':'Run'}</button><button class="dt-button" data-action="sim-fast">${v.fast?'1×':'4×'} speed</button><button class="dt-button" data-action="sim-save-a">Save A</button><button class="dt-button" data-action="sim-save-b">Save B</button></div><div class="metric-line"><span>Playback</span><strong>${v.progress}% · ${v.running?'Running':v.progress===100?'Complete':'Paused'}</strong></div><div class="progress"><i style="width:${v.progress}%"></i></div>`) +
    section('Projected outcome',`<div class="kpi-grid">${metric('Energy',outcome.energy,'kWh','Per sample hour')}${metric('Throughput',outcome.throughput,'u/h','Model estimate')}${metric('Cycle time',outcome.cycle,'min','Lower is better')}${metric('Yield',outcome.yield,'%','Estimated')}</div><div class="metric-line"><span>Bottleneck</span><strong>${outcome.bottleneck}</strong></div>`) +
    section('Side-by-side comparison',`<div class="metric-line"><span>Run A</span><strong>${v.runA?`${v.runA.energy} kWh · ${v.runA.yield}% yield`:'Not saved'}</strong></div><div class="metric-line"><span>Run B</span><strong>${v.runB?`${v.runB.energy} kWh · ${v.runB.yield}% yield`:'Not saved'}</strong></div><p class="muted">These are simple illustrative equations, not calibrated engineering predictions.</p>`) +
    section('Process flow & bottleneck',`<label class="dt-field">Flow rate <output>${v.flow}%</output><input class="range" data-sim="flow" type="range" min="20" max="120" value="${v.flow}" /></label><div class="metric-line"><span>Intake → AHU → Rooms</span><strong>${v.flow}%</strong></div><div class="progress"><i style="width:${Math.min(v.flow,100)}%"></i></div><p class="muted">Adjust flow to see cycle time and yield changes.</p>`);
  }
  function simulate(v){return {energy:Math.round(10+v.load*.15+v.speed*.07+Math.max(0,v.ambient-22)*.4),throughput:Math.round(v.flow*1.6+v.speed*.55),cycle:(18-v.flow*.06-v.speed*.03+v.load*.02).toFixed(1),yield:Math.max(70,Math.round(96-Math.abs(v.flow-75)*.1-Math.max(0,v.load-90)*.18)),bottleneck:v.flow<55?'Intake flow':v.speed<55?'Air handling':'No major constraint'};}
  function controls(){const c=state.control;return head('06 / CONTROL','Remote controls','A disconnected control sandbox. Changes stay in this browser.')+
    `<div class="note-box">Physical controls are disabled because no actuator gateway, authentication service, or safety system is connected.</div>`+
    section('Demo role',`<label class="dt-field">Active role<select class="dt-input" id="role-select"><option ${state.role==='Viewer'?'selected':''}>Viewer</option><option ${state.role==='Operator'?'selected':''}>Operator</option><option ${state.role==='Administrator'?'selected':''}>Administrator</option></select></label><p class="muted">Role selection is a UI demonstration, not authentication.</p>`) +
    section('Actuators & setpoints',`<div class="metric-line"><span>Supply fan</span><strong>${c.fan?'On':'Off'}</strong></div><button class="dt-button full" data-action="fan">Toggle demo fan</button><label class="dt-field">Valve position <output>${c.valve}%</output><input class="range" id="valve-position" type="range" min="0" max="100" value="${c.valve}" /></label><button class="dt-button full" data-action="valve">Apply valve to demo</button><label class="dt-field">Temperature setpoint<input class="dt-input" id="setpoint" type="number" min="16" max="30" step="0.5" value="${c.setpoint}" /></label><button class="dt-button full" data-action="setpoint">Apply setpoint to demo</button>`) +
    section('Safety interlock',`<label class="field-row"><span>Require confirmation</span><input id="interlock" type="checkbox" ${c.interlock?'checked':''} /></label><p class="muted">Confirmation applies only to simulated local actions. A real control link would need server-side interlocks and authorization.</p>`);
  }
  function integrations(){return head('07 / ENTERPRISE','Integrations & lineage','Connection inventory and sample data provenance.')+
    section('Connection status',`<div class="metric-line"><span>Microsoft Fabric</span><span class="pill">Unconnected</span></div><div class="metric-line"><span>ERP inventory</span><span class="pill">Unconnected</span></div><div class="metric-line"><span>MES process</span><span class="pill">Unconnected</span></div><div class="metric-line"><span>CMMS tickets</span><span class="pill">Unconnected</span></div>`) +
    section('Data lineage',`<div class="metric-line"><span>Geometry</span><strong>three-storey-demo.ifc</strong></div><div class="metric-line"><span>Optimized render</span><strong>three-storey-demo.frag</strong></div><div class="metric-line"><span>Element identity</span><strong>IFC GUID</strong></div><div class="metric-line"><span>Metrics</span><strong>Local generator</strong></div><p class="muted">No data is fetched from Microsoft Fabric in this demo.</p>`) +
    section('API endpoint planning',`<label class="dt-field">Endpoint label<input class="dt-input" id="endpoint-label" placeholder="e.g. Fabric telemetry API" /></label><label class="dt-field">Endpoint URL<input class="dt-input" id="endpoint-url" type="url" placeholder="https://your-api.example/telemetry" /></label><button class="dt-button full" data-action="save-endpoint">Save plan locally</button><div class="list">${state.endpoints.map(x=>`<div class="metric-line"><span>${esc(x.label)}</span><span class="pill">Planned</span></div>`).join('')}</div><p class="muted">This records a plan only. It never sends credentials or network requests.</p>`) +
    section('Workflow demos',`<div class="small-actions"><button class="dt-button" data-action="ticket">Create demo ticket</button><button class="dt-button" data-action="inventory">Simulate ERP sync</button></div><p class="muted">${state.workOrders.length} local tickets created this session.</p>`);
  }
  function governance(){return head('08 / GOVERNANCE','Roles & audit','Demonstration permissions and action history.')+
    section('Role-based access',`<label class="dt-field">Demo role<select class="dt-input" id="role-select"><option ${state.role==='Viewer'?'selected':''}>Viewer</option><option ${state.role==='Operator'?'selected':''}>Operator</option><option ${state.role==='Administrator'?'selected':''}>Administrator</option></select></label><div class="metric-line"><span>Viewer</span><strong>Inspect</strong></div><div class="metric-line"><span>Operator</span><strong>Demo controls</strong></div><div class="metric-line"><span>Administrator</span><strong>Demo controls + plans</strong></div><p class="muted">These UI roles do not protect data or authenticate users.</p>`) +
    section('Cybersecurity monitor',`<div class="metric-line"><span>External API calls</span><strong>0</strong></div><div class="metric-line"><span>Physical commands</span><strong>0</strong></div><div class="metric-line"><span>Connection state</span><span class="pill">Offline demo</span></div>`) +
    section('Audit history',`<div class="small-actions"><button class="dt-button" data-action="audit-json">Export JSON ↓</button></div><div class="audit-list">${state.audit.map(a=>`<div>${esc(a.time)} · ${esc(a.role)} · ${esc(a.action)}</div>`).join('')||'<p class="muted">Actions in this session appear here.</p>'}</div>`);
  }
  const views={overview,spatial,telemetry:telemetryPanel,analytics,simulation,controls,integrations,governance};
  function render(){ $('panel-content').innerHTML=views[state.view]();document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});renderRight();renderTime();$('map-overlay').innerHTML='<span class="map-point"></span><span class="map-label">Sample Building · '+esc(state.mapLayer)+' sample</span>' }
  function renderRight(){const s=current();$('kpi-grid').innerHTML=metric('Temperature',s.temperature,'°C','Sample',s.temperature>24?'attention':'')+metric('Power',s.power,'kW','Sample',s.power>22?'attention':'')+metric('Vibration',s.vibration,'mm/s','Sample',s.vibration>2.8?'attention':'')+metric('Uptime',s.uptime,'%','Sample');$('incident-preview').innerHTML=state.incidents.filter(x=>!x.cleared).slice(0,2).map(i=>incidentHtml(i)).join('')||'<p class="muted">No active incidents.</p>';if(state.selected){const e=byGuid.get(state.selected);$('selection-empty').hidden=false;$('selection-detail').hidden=true;if(e){$('selection-empty').hidden=true;$('selection-detail').hidden=false;$('selected-type').textContent=e.type.replace(/^Ifc/,'').toUpperCase();$('selected-name').textContent=e.name;$('selected-guid').textContent=e.guid;$('selected-status').textContent=telemetry.elementStates?.[e.guid]||'No linked sensor';const storey=storeyNameByGuid.get(storeyByGuid.get(e.guid));$('selected-floor').textContent=storey?`Level ${storey}`:'Unassigned'}}else{$('selection-empty').hidden=false;$('selection-detail').hidden=true}}
  function renderTime(){const slider=$('time-slider');if(!slider)return;const offset=60-state.minute;slider.value=state.minute;$('time-label').textContent=offset===0?'Now · sample state':`T−${offset} min · sample state`;const ref=state.compare==='off'?null:sampleAt(Number(state.compare),telemetry);$('time-diff').textContent=ref?`${(current().temperature-ref.temperature)>=0?'+':''}${(current().temperature-ref.temperature).toFixed(1)} °C`:'—';const reading=$('telemetry-current');if(reading){const units={temperature:'°C',power:'kW',vibration:'mm/s',humidity:'%',throughput:'units/h'};reading.textContent=`${current()[state.metric]} ${units[state.metric]}`}}
  function monitorSample(){const s=current();for(const [key,threshold,title] of [['temperature',24,'Automatic sample temperature alert'],['power',22,'Automatic sample power alert'],['vibration',2.8,'Automatic sample vibration alert']]){if(s[key]<=threshold||state.autoAlerts.has(key))continue;state.autoAlerts.add(key);state.incidents.unshift({id:Date.now()+state.autoAlerts.size,severity:'warning',title,minute:state.minute,ack:false,cleared:false,cause:`Sample sensor → ${key} threshold → operator review`});audit(`Auto-triggered ${key} sample alert`);toast(`${title} added to incidents.`)}}
  function setView(view){if(!views[view])return;state.view=view;render();document.querySelector('.sidebar').scrollTop=0;audit(`Opened ${labels[view]}`)}
  function setSelected(guid){state.selected=guid;renderRight();if(state.view==='spatial')render()}
  async function confirmDemo(title,message,action){if(state.role==='Viewer'){toast('Select Operator or Administrator to change demo controls.');return}if(state.control.interlock){$('confirm-title').textContent=title;$('confirm-message').textContent=message;const dialog=$('confirm-dialog');dialog.showModal();await new Promise(resolve=>dialog.addEventListener('close',()=>{if(dialog.returnValue==='confirm')action();resolve()},{once:true}))}else action()}
  document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view],[data-go]');if(nav){setView(nav.dataset.view||nav.dataset.go);return}const button=e.target.closest('[data-action]');if(!button)return;const a=button.dataset.action;try{
    if(a==='category'){state.category=button.dataset.category==='all'?null:button.dataset.category;await actions.category(state.category);render();audit(`Category ${state.category||'all'}`)}
    else if(a==='select'){const guid=button.dataset.guid;setSelected(guid);await actions.select(guid);await actions.focus(guid);audit('Selected and framed asset '+guid)}
    else if(a==='add-selection'){state.selectedMany.add(state.selected);render();toast('Asset added to working set.')}
    else if(a==='isolate-set'){await actions.isolate([...state.selectedMany]);toast(`Isolated ${state.selectedMany.size} assets.`)}
    else if(a==='clear-set'){state.selectedMany.clear();await actions.category(null);render()}
    else if(a==='map-toggle'){$('map-overlay').hidden=!$('map-overlay').hidden;render();toast('Map overlay uses illustrative local data.')}
    else if(a==='geofence'){state.geofence=!state.geofence;render();audit(`Demo geofence ${state.geofence?'enabled':'disabled'}`)}
    else if(a==='ack'||a==='clear'){const item=state.incidents.find(i=>i.id===Number(button.dataset.id));if(item){if(a==='ack')item.ack=true;else item.cleared=true;audit(`${a==='ack'?'Acknowledged':'Cleared'} sample incident ${item.id}`);render()}}
    else if(a==='trigger-alarm'){state.incidents.unshift({id:Date.now(),severity:current().temperature>24?'warning':'info',title:'Operator-triggered sample threshold alert',minute:state.minute,ack:false,cleared:false,cause:'Sample sensor → threshold test'});audit('Triggered sample alarm');render();toast('Sample alert added.')}
    else if(a==='noise'){state.filter=!state.filter;render()}
    else if(a==='csv'||a==='json'){const rows=Array.from({length:61},(_,minute)=>({minute,...sampleAt(minute,telemetry)}));if(a==='json')download('sample-sample-telemetry.json',JSON.stringify(rows,null,2),'application/json');else download('sample-sample-telemetry.csv',['minute,temperatureC,humidityPercent,powerKw,vibrationMmS,uptimePercent,throughputPerHour',...rows.map(r=>`${r.minute},${r.temperature},${r.humidity},${r.power},${r.vibration},${r.uptime},${r.throughput}`)].join('\n'),'text/csv');audit(`Exported sample ${a.toUpperCase()}`)}
    else if(a==='work-order'||a==='ticket'){state.workOrders.push({id:`WO-${1000+state.workOrders.length}`,time:new Date().toISOString(),asset:'Supply fan',status:'Draft'});audit('Created local demo work order');render();toast('Draft demo work order created locally.')}
    else if(a==='feedback'){state.feedback.push({label:button.dataset.value,time:state.minute});audit(`Anomaly feedback: ${button.dataset.value}`);render();toast('Feedback saved in this session.')}
    else if(a==='time-play'){state.playing=!state.playing;if(state.playing){if(state.minute===60)state.minute=0;playTimer=setInterval(()=>{state.minute=Math.min(60,state.minute+1);monitorSample();render();if(state.minute===60){clearInterval(playTimer);state.playing=false;render()}},800)}else clearInterval(playTimer);render()}
    else if(a==='replay-incident'){const last=state.incidents.find(i=>!i.cleared);state.minute=Math.max(0,(last?.minute??60)-5);render();toast('Showing five sample minutes before the selected incident.')}
    else if(a==='sim-run'){state.sim.running=!state.sim.running;if(state.sim.running){if(state.sim.progress===100)state.sim.progress=0;simTimer=setInterval(()=>{state.sim.progress=Math.min(100,state.sim.progress+(state.sim.fast?4:1));if(state.view==='simulation')render();if(state.sim.progress===100){clearInterval(simTimer);state.sim.running=false;audit('Simulation completed');if(state.view==='simulation')render()}},500)}else clearInterval(simTimer);audit(`Simulation ${state.sim.running?'started':'paused'}`);render()}
    else if(a==='sim-fast'){state.sim.fast=!state.sim.fast;render()}
    else if(a==='sim-save-a'||a==='sim-save-b'){state.sim[a==='sim-save-a'?'runA':'runB']=simulate(state.sim);audit(`Saved sample run ${a==='sim-save-a'?'A':'B'}`);render()}
    else if(a==='fan')await confirmDemo('Toggle demo fan','This changes only the local simulated fan state.',()=>{state.control.fan=!state.control.fan;audit(`Demo fan ${state.control.fan?'on':'off'}`);render()});
    else if(a==='valve')await confirmDemo('Set demo valve','This changes only the local simulated valve position.',()=>{state.control.valve=Number($('valve-position').value);audit(`Demo valve ${state.control.valve}%`);render()});
    else if(a==='setpoint')await confirmDemo('Set demo temperature','This changes only the local simulated setpoint.',()=>{state.control.setpoint=Number($('setpoint').value);audit(`Demo setpoint ${state.control.setpoint} °C`);render()});
    else if(a==='save-endpoint'){if(state.role!=='Administrator'){toast('Select Administrator to save endpoint plans.');return}const label=$('endpoint-label').value.trim(),url=$('endpoint-url').value.trim();if(!label||!/^https?:\/\//.test(url)){toast('Enter a label and http(s) URL.');return}state.endpoints.push({label,url});audit('Saved endpoint plan '+label);render();toast('Endpoint plan saved locally. No connection attempted.')}
    else if(a==='inventory'){audit('Simulated ERP inventory sync');toast('Inventory sync simulated; no ERP connection.')}
    else if(a==='audit-json'){download('sample-demo-audit.json',JSON.stringify(state.audit,null,2),'application/json')}
  }catch(error){console.error(error);toast(`Action failed: ${error.message}`)}});
  document.addEventListener('input',e=>{if(e.target.id==='asset-search'){state.query=e.target.value;const pos=e.target.selectionStart;render();$('asset-search').focus();$('asset-search').setSelectionRange(pos,pos)}else if(e.target.dataset.sim){state.sim[e.target.dataset.sim]=Number(e.target.value);e.target.parentElement.querySelector('output').textContent=`${e.target.value}${e.target.dataset.sim==='ambient'?' °C':'%'}`}else if(e.target.id==='valve-position'){e.target.parentElement.querySelector('output').textContent=`${e.target.value}%`}else if(e.target.id==='time-slider'){state.minute=Number(e.target.value);monitorSample();renderRight();renderTime()}else if(e.target.id==='interlock'){state.control.interlock=e.target.checked;audit(`Demo interlock ${e.target.checked?'enabled':'disabled'}`)} });
  document.addEventListener('change',e=>{if(e.target.dataset.sim)render();else if(e.target.id==='metric-select'){state.metric=e.target.value;render()}else if(e.target.id==='map-layer'){state.mapLayer=e.target.value;render()}else if(e.target.id==='role-select'){state.role=e.target.value;audit(`Switched demo role to ${state.role}`);render()}else if(e.target.id==='compare-time'){state.compare=e.target.value;renderTime()}});
  $('clear-selection').addEventListener('click',()=>{state.selected=null;actions.clearSelection();renderRight()});
  $('focus-selection').addEventListener('click',()=>{if(state.selected)actions.focus(state.selected)});
  $('help-button').addEventListener('click',()=>toast('Sample Building viewer · model geometry is synthetic IFC; operations, GIS, analytics, controls, and integrations are local demonstrations.'));
  $('details-toggle').addEventListener('click',()=>{const open=$('inspector').classList.toggle('open');$('details-toggle').setAttribute('aria-expanded',String(open))});
  $('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
  render();
  return {state,setSelected,setView,toast,band:(guid)=>band(byGuid.get(guid),bounds),bounds};
}
